// milestones/milestone4/angular-app/src/app/components/verse-list/verse-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { VerseService } from '../../services/verse.service';
import { BibleVerse } from '../../models/verse.model';

@Component({
  selector: 'app-verse-list',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="container py-4">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="mb-0 fw-bold text-primary">📖 Bible Verses</h2>
        <a routerLink="/verses/new" class="btn btn-primary">
          ➕ Add New Verse
        </a>
      </div>

      <!-- Search Bar -->
      <div class="card shadow-sm mb-4">
        <div class="card-body">
          <div class="row g-3 align-items-end">
            <div class="col-md-6">
              <label class="form-label fw-semibold">Search</label>
              <input type="text" class="form-control" [(ngModel)]="searchTerm"
                placeholder="e.g. grace, love, shepherd..." (keyup.enter)="search()">
            </div>
            <div class="col-md-3">
              <label class="form-label fw-semibold">Testament</label>
              <select class="form-select" [(ngModel)]="testament">
                <option value="ALL">All</option>
                <option value="OT">Old Testament</option>
                <option value="NT">New Testament</option>
              </select>
            </div>
            <div class="col-md-3 d-flex gap-2">
              <button class="btn btn-primary w-100" (click)="search()">🔍 Search</button>
              <button class="btn btn-outline-secondary" (click)="reset()">✕</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Loading -->
      <div *ngIf="loading" class="text-center py-5">
        <div class="spinner-border text-primary"></div>
        <p class="mt-2 text-muted">Loading verses...</p>
      </div>

      <!-- Error -->
      <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

      <!-- Empty -->
      <div *ngIf="!loading && !error && verses.length === 0" class="text-center py-5 text-muted">
        <p class="fs-4">No verses found.</p>
        <a routerLink="/verses/new" class="btn btn-outline-primary mt-2">Add the first verse</a>
      </div>

      <!-- Results count -->
      <p *ngIf="!loading && verses.length > 0" class="text-muted small mb-3">
        Showing {{ verses.length }} verse{{ verses.length !== 1 ? 's' : '' }}
      </p>

      <!-- Verse Cards -->
      <div class="row g-3">
        <div class="col-12" *ngFor="let verse of verses">
          <div class="card shadow-sm border-0 hover-card">
            <div class="card-body d-flex justify-content-between align-items-start">
              <div class="flex-grow-1">
                <div class="d-flex align-items-center gap-2 mb-1">
                  <span class="badge bg-primary">{{ verse.book_name }} {{ verse.chapter }}:{{ verse.verse_num }}</span>
                  <span class="badge" [ngClass]="verse.testament === 'OT' ? 'bg-warning text-dark' : 'bg-success'">
                    {{ verse.testament }}
                  </span>
                </div>
                <p class="mb-0 text-muted fst-italic">"{{ verse.text | slice:0:120 }}{{ verse.text.length > 120 ? '...' : '' }}"</p>
              </div>
              <div class="d-flex gap-2 ms-3 flex-shrink-0">
                <a [routerLink]="['/verses', verse.id]" class="btn btn-sm btn-outline-primary">View</a>
                <a [routerLink]="['/verses', verse.id, 'edit']" class="btn btn-sm btn-outline-secondary">Edit</a>
                <button class="btn btn-sm btn-outline-danger" (click)="deleteVerse(verse)">Delete</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`.hover-card:hover { border-left: 4px solid #0d6efd !important; transition: all 0.15s ease; }`]
})
export class VerseListComponent implements OnInit {
  verses: BibleVerse[] = [];
  searchTerm = '';
  testament = 'ALL';
  loading = false;
  error = '';

  constructor(private verseService: VerseService) {}

  ngOnInit(): void { this.search(); }

  search(): void {
    this.loading = true;
    this.error = '';
    this.verseService.searchVerses(this.searchTerm || undefined, this.testament).subscribe({
      next: v => { this.verses = v; this.loading = false; },
      error: e => { this.error = 'Failed to load verses. Is the API server running?'; this.loading = false; }
    });
  }

  reset(): void { this.searchTerm = ''; this.testament = 'ALL'; this.search(); }

  deleteVerse(verse: BibleVerse): void {
    if (!confirm(`Delete "${verse.book_name} ${verse.chapter}:${verse.verse_num}"? This cannot be undone.`)) return;
    this.verseService.deleteVerse(verse.id).subscribe({
      next: () => this.verses = this.verses.filter(v => v.id !== verse.id),
      error: () => alert('Failed to delete verse.')
    });
  }
}

// milestones/milestone5/react-app/src/components/VerseList/VerseList.tsx
import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { BibleVerse } from '../../models/types';
import { searchVerses, deleteVerse } from '../../services/verseService';

export default function VerseList() {
  const [verses, setVerses]     = useState<BibleVerse[]>([]);
  const [query, setQuery]       = useState('');
  const [testament, setTestament] = useState('ALL');
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState('');

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      setVerses(await searchVerses(query || undefined, testament));
    } catch {
      setError('Could not load verses. Is the API running on port 3000?');
    } finally { setLoading(false); }
  }, [query, testament]);

  useEffect(() => { load(); }, []);

  const handleDelete = async (verse: BibleVerse) => {
    if (!confirm(`Delete ${verse.book_name} ${verse.chapter}:${verse.verse_num}?`)) return;
    await deleteVerse(verse.id);
    setVerses(v => v.filter(x => x.id !== verse.id));
  };

  return (
    <div className="container py-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2 className="fw-bold text-primary mb-0">📖 Bible Verses</h2>
        <Link to="/verses/new" className="btn btn-primary">➕ Add New Verse</Link>
      </div>

      {/* Search */}
      <div className="card shadow-sm mb-4">
        <div className="card-body">
          <div className="row g-3 align-items-end">
            <div className="col-md-6">
              <label className="form-label fw-semibold">Search</label>
              <input className="form-control" value={query} onChange={e => setQuery(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && load()} placeholder="e.g. grace, love, shepherd..." />
            </div>
            <div className="col-md-3">
              <label className="form-label fw-semibold">Testament</label>
              <select className="form-select" value={testament} onChange={e => setTestament(e.target.value)}>
                <option value="ALL">All</option>
                <option value="OT">Old Testament</option>
                <option value="NT">New Testament</option>
              </select>
            </div>
            <div className="col-md-3 d-flex gap-2">
              <button className="btn btn-primary w-100" onClick={load}>🔍 Search</button>
              <button className="btn btn-outline-secondary" onClick={() => { setQuery(''); setTestament('ALL'); }}>✕</button>
            </div>
          </div>
        </div>
      </div>

      {loading && <div className="text-center py-5"><div className="spinner-border text-primary" /><p className="mt-2 text-muted">Loading...</p></div>}
      {error   && <div className="alert alert-danger">{error}</div>}
      {!loading && !error && verses.length === 0 && (
        <div className="text-center py-5 text-muted">
          <p className="fs-4">No verses found.</p>
          <Link to="/verses/new" className="btn btn-outline-primary mt-2">Add the first verse</Link>
        </div>
      )}

      {!loading && verses.length > 0 && (
        <p className="text-muted small mb-3">Showing {verses.length} verse{verses.length !== 1 ? 's' : ''}</p>
      )}

      <div className="row g-3">
        {verses.map(verse => (
          <div className="col-12" key={verse.id}>
            <div className="card shadow-sm border-0">
              <div className="card-body d-flex justify-content-between align-items-start">
                <div className="flex-grow-1">
                  <div className="d-flex gap-2 mb-1">
                    <span className="badge bg-primary">{verse.book_name} {verse.chapter}:{verse.verse_num}</span>
                    <span className={`badge ${verse.testament === 'OT' ? 'bg-warning text-dark' : 'bg-success'}`}>{verse.testament}</span>
                  </div>
                  <p className="mb-0 text-muted fst-italic">
                    "{verse.text.length > 120 ? verse.text.slice(0, 120) + '...' : verse.text}"
                  </p>
                </div>
                <div className="d-flex gap-2 ms-3 flex-shrink-0">
                  <Link to={`/verses/${verse.id}`} className="btn btn-sm btn-outline-primary">View</Link>
                  <Link to={`/verses/${verse.id}/edit`} className="btn btn-sm btn-outline-secondary">Edit</Link>
                  <button className="btn btn-sm btn-outline-danger" onClick={() => handleDelete(verse)}>Delete</button>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
